const errors = {
  GET_BOOK_BY_ID: "GET BY ID MODEL METHOD SHOULD RETURN ONLY ONE OBJECT",
  BOOK_ALREADY_EXISTS: "BOOK_ALREADY_EXISTS",
  BOOK_INFO_NOT_FOUND: "BOOK_INFO_NOT_FOUND",
  BOOK_POST_VALIDATION_ERROR: "BOOK_POST_VALIDATION_ERROR",
  BOOK_PATCH_VALIDATION_ERROR: "BOOK_PATCH_VALIDATION_ERROR",
  BY_AUTHOR_VALIDATION_ERROR: "BY_AUTHOR_VALIDATION_ERROR",
}

export default errors
