const errors = {
  GET_BOOK_BY_ID: "GET BY ID MODEL METHOD SHOULD RETURN ONLY ONE OBJECT",
  BOOK_DOES_NOT_EXIST: "BOOK_DOES_NOT_EXIST",
  BOOK_INFO_NOT_FOUND: "BOOK_INFO_NOT_FOUND",
}

export default errors
